"""Update e user model

Revision ID: 0829e0f89654
Revises: 609f42fa9389
Create Date: 2024-02-19 21:54:38.931642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0829e0f89654'
down_revision = '609f42fa9389'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
