"""Update forgot_password table

Revision ID: 52a8d00bb3b7
Revises: 0bc292aa758f
Create Date: 2024-02-28 18:53:21.694231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52a8d00bb3b7'
down_revision = '0bc292aa758f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forgot_password', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_email', sa.String(), nullable=False))
        batch_op.create_unique_constraint(None, ['user_email'])
        batch_op.drop_constraint('fk_forgot_password_user_id_users', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forgot_password', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_forgot_password_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('user_email')

    # ### end Alembic commands ###
