"""Updated models

Revision ID: 609f42fa9389
Revises: 95a6261cf087
Create Date: 2024-02-19 21:30:31.933121

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '609f42fa9389'
down_revision = '95a6261cf087'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carbon_footprint_counts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.drop_constraint('fk_carbon_footprint_counts_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_carbon_footprint_counts_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('date')

    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_donations_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_donations_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('educational_resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=False))

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=False))

    with op.batch_alter_table('impact_monitorings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_impact_monitorings_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_impact_monitorings_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.alter_column('website',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=False))
        batch_op.drop_column('manufacturer_link')
        batch_op.drop_column('brand')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.drop_constraint('fk_reviews_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_reviews_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('date_posted')

    with op.batch_alter_table('track_goals', schema=None) as batch_op:
        batch_op.drop_constraint('fk_track_goals_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_track_goals_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_events', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_events_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_events_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))
        batch_op.drop_column('last_login')
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('last_login', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('image_url')

    with op.batch_alter_table('user_events', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_events_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_user_events_user_id_users', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('track_goals', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_track_goals_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_track_goals_user_id_users', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_posted', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_reviews_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_reviews_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.drop_column('created_at')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('manufacturer_link', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('image_url')

    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.alter_column('website',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('impact_monitorings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_impact_monitorings_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_impact_monitorings_user_id_users', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('educational_resources', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_donations_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_donations_user_id_users', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('carbon_footprint_counts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_carbon_footprint_counts_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_carbon_footprint_counts_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
