"""Adjust feedback model

Revision ID: 95a6261cf087
Revises: 6ce7698c015c
Create Date: 2024-02-19 14:29:17.508527

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '95a6261cf087'
down_revision = '6ce7698c015c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_forms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('feedback_message', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
        batch_op.drop_constraint('fk_feedback_forms_user_id_users', type_='foreignkey')
        batch_op.drop_column('feedback_type')
        batch_op.drop_column('feedback_text')
        batch_op.drop_column('user_id')
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback_forms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('feedback_text', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('feedback_type', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('fk_feedback_forms_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.drop_column('created_at')
        batch_op.drop_column('feedback_message')
        batch_op.drop_column('email')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
